global thhd pio6rw nikki output_dir var_name_set var_ename_set ...
   var_req_set var_unit_set var_range var_linORlog l_da ampORbin bintype ...
   conf2grid

% model configs
addpath('ramsfuncs/')
ampORbin={'amp' 'bin'};
bintype={'tau' 'sbm'};

ampbin_lsty = {'--','-'};
ampbin_lwid = [2 1];

pio6rw=3.1415926535/6*1000;

% thresholds to be considered as clouds 
thhd.cloud_mr_th=[1e-7 1e-2]; % g/kg, threshold for mixing ratio
thhd.rain_mr_th=[1e-8 1e-2];
thhd.cloud_n_th=[1e-1 inf]; % #/cc, threshold for droplet number concentration
thhd.rain_n_th=[1e-4 inf];
thhd.cwp_th=[1 inf]; % g/m2 cloud water path threshold
thhd.rwp_th=[1e-1 inf]; % g/m2 rain water path threshold
thhd.meanD_th=[0 inf];
thhd.sppt_th=[0 inf]; % mm/hr surface precipitation

% set the current date as nikki if unset
if ~exist('nikki')
    nikki=datestr(date,'YYYY-mm-dd');
end

% convert iconf to grid location
conf2grid = {[1,1], [1,2], [1,3], [1,4], [1,5], ...
                    [2,2], [2,3], [2,4], [2,5], ...
                           [3,3], [3,4], [3,5], ...
                                  [4,4], [4,5], ...
                                         [5,5], ...
            };

% dir of the model output
% output_dir='/Volumes/ESSD/AMP output/';
% output_dir='../github/rams/output/';
output_dir='/group/aigelgrp2/arthurhu/RAMS/';

% load these python colormap
ngrad=21;
if ~exist('cmaps','var')
   cmaps.Blues=getPyPlot_cMap('Blues',10);
   cmaps.Blues_s=getPyPlot_cMap('Blues');
   cmaps.rainbow=getPyPlot_cMap('rainbow',20);
   cmaps.coolwarm=getPyPlot_cMap('coolwarm',10);
   cmaps.coolwarm_11=getPyPlot_cMap('coolwarm',11);
   cmaps.coolwarm_s=getPyPlot_cMap('coolwarm');
   cmaps.coolwarm_r=getPyPlot_cMap('coolwarm_r',10);
   cmaps.coolwarm_r11=getPyPlot_cMap('coolwarm_r',11);
   cmaps.BrBG20=getPyPlot_cMap('BrBG',20);
   cmaps.BrBG=getPyPlot_cMap('BrBG',ngrad)*.9;
   cmaps.BrBG=repelem(cmaps.BrBG,floor(256/ngrad),1); 
   cmaps.flag3 = cmaps.coolwarm_r11([6 9 2],:);
   cmaps.flag3(1,:) = [1, 1, 1];
end

colororder=colororder;
color_order={};
for i=1:size(colororder,1)
   color_order{i}=colororder(i,:);
end

clear colororder

% variables: {{{
var_name_set = {'CWP','RWP','LWP',...
                'CWC','RWC','LWC',...
                'CNP','RNP','LNP',...
                'CNC','RNC','LNC',...
                'Rv','RH', ...
                'DSDm', 'DSDn','reldisp', ...
                'flagc','flagr',...
                'pres', 'temp', 'w',...
                'cloud_frac', 'meandc', 'meandr', ...
                'nu_c','nu_r',...
                'Dn_c','Dn_r',...
                'momc3','momr3',...
                'SS', 'wp_advdif','wp_cond','wp_theta',...
                'sppt',...
                };
var_ename_set = {'cloud water path','rain water path','liquid water path',... 3
                 'cloud water content','rain water content','liquid water content',... 6
                 'cloud num. path','rain num. path','liquid num. path',... 9
                 'cloud num. conc.','rain num. conc.','liquid num. conc.',... 12
                 'mixing ratio','relative humidity',... 14
                 'DSD mass', 'DSD number', 'relative dispersion', ... 17
                 'flag (cloud)', 'flag (rain)', ... 19
                 'pressure', 'temperature', 'vertical velocity'... 22
                 'cloud frac', 'D_{mc}', 'D_{mr}', ... 25
                 'nu_c','nu_r', ... 27
                 'Dn_c','Dn_r',... 29
                 'momc3','momr3',...31
                 'supersaturation', 'wp adv','wp cond','wp theta'... 35
                 'mean surface precip.', ... 36
                 };
var_req_set = {{'RCP'},{'RRP'},{'RCP','RRP'},...
               {'RCP'},{'RRP'},{'RCP','RRP'},...
               {'CCP'}, {'CRP'}, {'CCP','CRP'}, ... 
               {'CCP'}, {'CRP'}, {'CCP','CRP'}, ... 
               {'RV'},{'RV'}, ...
               {'FFCD'},{'FFCDN'},{'RELDISP'},...
               {'GUESSC3'}, {'GUESSR3'}, ...
               {'PI'},{'THETA'},{'WP'}, ...
               {'GUESSC6'}, {'RCP','CCP'}, {'RRP','CRP'}, ...
               {'GUESSC1'}, {'GUESSR1'}, ...
               {'GUESSC2'}, {'GUESSR2'}, ...
               {'DMOMC3'}, {'DMOMR3'}, ...
               {'RV'},{'WP_ADVDIF'},{'WP_BUOY_COND'},{'WP_BUOY_THETA'},...
               {'PCPRR'}, ...
               };
var_unit_set = {' [g/m^2]', ' [g/m^2]',' [g/m^2]', ...
                ' [g/kg]', ' [g/kg]', ' [g/kg]', ...
                ' [1/m^2]', ' [1/m^2]', ' [1/m^2]', ...
                ' [1/kg]', ' [1/kg]', ' [1/kg]', ...
                ' [kg/kg]',' %', ...
                ' [kg/kg]', ' [1/kg]', '', ...
                '','',...
                ' [hPa]', ' [K]', ' [m/s]'...
                '', ' [\mum]', ' [\mum]', ...
                '','',...
                ' [m]', ' [m]',...
                '','',...
                '',' [m/s]',' [m/s]',' [m/s]',...
                ' [kg/m^2/s]', ...
                };
var_range = {[1e-2 1e4],[1e-2 1e4],[1e-2 1e4], ...
             [1e-5 1e0], [1e-5 1e0], [1e-5 1e0], ...
             [],[],[], ...
             [],[],[], ...
             [],[], ...
             [],[],[0 1], ...
             [-1 1], [-1 1], ...
             [], [], [-.03 .03], ...
             [0 1], [0 80], [80 1000], ...
             [],[],...
             [1e-7 1e-5],[1e-6 1e-3],...
             [],[],...
             [-2 2], [-.03 .03], [-0.03 .03], [-0.03 .03], ...
             [], ...
             };
var_linORlog = {'log', 'log', 'log', ...
                'log', 'log', 'log', ...
                'log', 'log', 'log', ...
                'log', 'log', 'log', ...
                'lin', 'lin', ...
                'log', 'log', 'lin', ...
                'lin', 'lin', ...
                'lin', 'lin', 'lin', ...
                'lin', 'lin', 'log',...
                'lin','lin',...
                'log','log',...
                'log','log',...
                'lin', 'lin', 'lin', 'lin', ...
                'lin', ...
                };
% }}}

% output dir for the figures
plot_dir=['plots/rams/' nikki '/'];
if ~exist(plot_dir,'dir')
   mkdir(plot_dir)
end

% output dir for the vids
vid_dir=['vids/rams/' nikki '/'];
if ~exist(vid_dir,'dir')
   mkdir(vid_dir)
end
